// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function failure(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}
function ok(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my profile",
  description: "Get the signed-in EntreVault user's profile: username, name, registration status, USDT balance, referral code and wallet address.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("profiles").select(
      "username, first_name, last_name, email, country, registration_status, usdt_balance, referral_code, wallet_address, minipay_number, created_at"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return failure(error.message);
    if (!data) return failure("No profile found for this account.");
    return ok(data, { profile: data });
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_courses_default = defineTool2({
  name: "list_courses",
  title: "List courses",
  description: "List EntreVault content creation and marketing courses available to the signed-in user.",
  inputSchema: {
    category: z.string().optional().describe("Filter by course category."),
    limit: z.number().int().optional().describe("Max courses to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("courses").select("*").order("created_at", { ascending: false }).limit(take);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return ok(data ?? [], { courses: data ?? [] });
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_notifications_default = defineTool3({
  name: "list_notifications",
  title: "List my notifications",
  description: "List the signed-in user's in-app EntreVault notifications, newest first.",
  inputSchema: {
    unread_only: z2.boolean().optional().describe("Only return unread notifications."),
    limit: z2.number().int().optional().describe("Max notifications to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("notifications").select("id, type, title, message, link, read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(take);
    if (unread_only) query = query.eq("read", false);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return ok(data ?? [], { notifications: data ?? [] });
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_sessions_default = defineTool4({
  name: "list_sessions",
  title: "List live classes",
  description: "List EntreVault live classes the signed-in user can access, newest upcoming first.",
  inputSchema: {
    course_id: z3.string().uuid().optional().describe("Filter by course id."),
    include_past: z3.boolean().optional().describe("Include sessions that already ended."),
    limit: z3.number().int().optional().describe("Max sessions to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id, include_past, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("live_sessions").select("id, title, description, course_id, starts_at, duration_minutes, status, timezone").order("starts_at", { ascending: true }).limit(take);
    if (course_id) query = query.eq("course_id", course_id);
    if (!include_past) query = query.gte("starts_at", new Date(Date.now() - 3 * 36e5).toISOString());
    const { data, error } = await query;
    if (error) return failure(error.message);
    return ok(data ?? [], { sessions: data ?? [] });
  }
});

// src/lib/mcp/tools/list-my-enrollments.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_enrollments_default = defineTool5({
  name: "list_my_enrollments",
  title: "List my enrollments",
  description: "List the signed-in user's course enrollments and their access status.",
  inputSchema: {
    limit: z4.number().int().optional().describe("Max enrollments to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("enrollments").select("id, course_id, status, enrolled_at, access_expires_at, courses(title, slug, level)").eq("user_id", ctx.getUserId()).order("enrolled_at", { ascending: false }).limit(take);
    if (error) return failure(error.message);
    return ok(data ?? [], { enrollments: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "ljhpnkleqfgudfqkebog";
var mcp_default = defineMcp({
  name: "entrevault-mcp",
  title: "EntreVault",
  version: "0.2.0",
  instructions: "Tools for EntreVault, a live learning platform teaching practical technology skills. Callers act as the signed-in user: read their profile, browse published courses, see their enrollments, upcoming live classes and notifications.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_courses_default,
    list_my_enrollments_default,
    list_sessions_default,
    list_notifications_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
